project_id = "hchfnnicseujpbkrxpxm"

[functions.ai-chat]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.ai-detector]
verify_jwt = true

[functions.ai-task-suggest]
verify_jwt = false
